### ISSUE TITLE
Sidebar navbar vanished on smartphone or tablet, only displayed for PC |version 1.0.2 + 1.0.3

### ISSUE THREAD

**Issue by marcq64** [creativetimofficial/ct-black-dashboard-pro-laravel#16]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version ( version 1.0.2 + 1.0.3 have the same issue )
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
Sidebar accessible (reduced, toggle button) when accessing application with smartphone or tablet.
Please describe the behavior you are expecting

# Current Behavior
What is the current behavior?
Sidebar vanish (same when I'm testing your online version : https://black-dashboard-pro-laravel.creative-tim.com/dashboard

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.
Don't think it is a bug, but I'm unable to parameter the sidebar in a manner that enable to be displayed for smartphone or tablet.
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
Go to https://black-dashboard-pro-laravel.creative-tim.com/dashboard
2. step 2
Open inspect element through context menu and click on the toggle device toolbar
3. you get it...
You can choose IPhoneX or IPad Pro and you will see that the sidebar completely vanished

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: PC
* Operating System: Windows
* Browser and Version: Chrome, Opera, Edge (latest versions)

## Failure Logs
No error

Thanks in advance for your advice, how I can solve this issue.

Cheers

Please include any relevant log snippets or files here.
IPhoneX
![image](https://user-images.githubusercontent.com/33374514/99066421-85ee8900-25db-11eb-8a33-da86170cb970.png)
IPadPro
![image](https://user-images.githubusercontent.com/33374514/99066498-a7e80b80-25db-11eb-84e8-fcb7345593dd.png)

**Comment by marcq64** [comment]
Hi, would appreciate some support here, thanks in advance

**Comment by teamupdivision** [comment]
Hi @marcq64,
Thanks for using our products.
We'll follow up with a reply shortly.
Best

**Comment by teamupdivision** [comment]
Hi @marcq64,

Thank you for your patience. We've gone ahead and fixed the issue. 

UPDIVISION

**Comment by marcq64** [comment]
Hi @teamupdivision 

Thanks a lot for this good news. 
As told, I'm running the version of your dashboard for Laravel 7.
Could you point me to the files which I need to replace (sorry I don't use github).
Thank you in advance,
Cheers,
Marc

**Comment by teamupdivision** [comment]
Hi @marcq64,

You can remove class "d-none" from this div: `<div class="navbar-wrapper d-none">`. You can find this in resources/views/layouts/navbars/navs/auth.blade.php.

UPDIVISION

**Comment by marcq64** [comment]
Hi @teamupdivision 

Thanks, I have removed the d-done, clear the caches, reloaded the page and tested with inspect, still no trace of the navbar as you can see :

![image](https://user-images.githubusercontent.com/33374514/99399893-db4ad300-2918-11eb-9cd1-afbf226ffa23.png)

**Comment by marcq64** [comment]
Hi @teamupdivision

Sorry to bother you, but  need a solution here or your dashboard is just useless, if I can't use it for other device than desktop, right. Thank you in advance for a solution.

**Comment by marcq64** [comment]
Hi @teamupdivision

I just have uploaded your last version for Laravel 8. And you have the same problem : no reduced sidebar or toggle button to display the sidebar. Toogle button is just for the navbar :

![image](https://user-images.githubusercontent.com/33374514/99495878-e39d1f80-29a5-11eb-8cde-764ea14a61b8.png)

**Comment by teamupdivision** [comment]
Hi @marcq64,

We'll follow up with a reply shortly.

UPDIVISION

**Comment by teamupdivision** [comment]
Hi @marcq64,

Thank you for your patience. 
We went ahead and tried to reproduce the bug, but did not succeed. 
Our recommendation is for you to try again to delete right class "d-none" from `<div class="navbar-wrapper d-none">` in resources/views/layouts/navbars/navs/auth.blade.php. 

You can use the below screenshots as a reference.

![Removing the d-none](https://user-images.githubusercontent.com/45566836/99519963-2efe0080-299b-11eb-9c49-b2e7746904d2.png)
![After removing the d-none1](https://user-images.githubusercontent.com/45566836/99520062-5228b000-299b-11eb-87e4-7ac9619cff2d.png)
![After removing the d-none2](https://user-images.githubusercontent.com/45566836/99520072-5523a080-299b-11eb-81ac-a94d95192888.png)

Looking forward to hearing from you!

UPDIVISION

P.S. If it does not work, let us know the browser and the OS you are getting this issue on so that we can further investigate.

**Comment by marcq64** [comment]
Hi @teamupdivision,

Thanks a lot for your support, appreciated. 

It was my mistake. As you can see on the first screen capture of my dashboard, I have changed the background-color of the dashboard to #ffffff. 

Since the ".navbar .navbar-toggler-bar" was set to #ffffff, we could not see the toggle button which was available all the time, I just haven't tried to click on the top upper left, what lead me today to found it out. Since I had erased the "d-none" class as per instruction and changed the color of the ".navbar .navbar-toggler-bar", the sidebar appeared (see attached screen captured).

Sorry guys to have wasted your time and thank you for the time spent trying to help me.

Cheers,

Marc

![image](https://user-images.githubusercontent.com/33374514/99612194-b1dc9500-2a47-11eb-9419-66ecde44ba32.png)

**Comment by teamupdivision** [comment]
Hi @marcq64,

We are glad that your problem is solved.
I will go ahead and close this ticket. If you will have any other issues or will need help in the future feel free to open a new ticket and we'll do our best to assist you.

Thank you,

UPDIVISION

P.S. If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients over here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
